<div class="h-screen">
	<svg
		xmlns="http://www.w3.org/2000/svg"
		xmlns:xlink="http://www.w3.org/1999/xlink"
		style=" shape-rendering: auto;"
		width="200px"
		height="200px"
		viewBox="0 0 100 100"
		preserveAspectRatio="xMidYMid"
		class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
	>
		<path
			d="M10 50A40 40 0 0 0 90 50A40 42.8 0 0 1 10 50"
			fill="#ffffff"
			stroke="none"
		>
			<animateTransform
				attributeName="transform"
				type="rotate"
				dur="1s"
				repeatCount="indefinite"
				keyTimes="0;1"
				values="0 50 51.4;360 50 51.4"
			/>
		</path>
		<!-- [ldio] generated by https://loading.io/ -->
	</svg>
</div>
